# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='newtwork',
            new_name='network',
        ),
    ]
