# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showapp', '0002_auto_20190916_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='RDate',
            field=models.DateField(),
        ),
    ]
